config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'
  post 'chatrooms', to: 'chatrooms#create'
  post 'photos', to: 'photos#create'

  resources :users
  resources :articles
  resources :categories, except: [:destroy]
  resources :comments
  resources :chatrooms, only: [:index, :show]
  resources :messages, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :description, presence: true, length: { minimum: 5 }

  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :comments, dependent: :destroy
  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @article = Article.order('id DESC').paginate(page: params[:page], per_page: 8)
  end

  def show
    @comment = @article.comments.paginate(page: params[:page], per_page: 10)
  end

  def new
    @article = Article.new
    @photo = @article.photos.build
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      puts(params[:post_attachments])
      if params[:post_attachments]
        params[:post_attachments]['avatar'].each do |a|
          @article.photos.create!(photo_url: a, article: @article)
        end
      end

      flash[:notice] = "#{@article.title} 을 작성했습니다"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "#{@article.title} 이 업데이트 됐습니다"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :description, :user_id, category_ids: [], post_attachments_attributes: [:id, :avatar])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user && !admin?
      flash[:alert] = "게시글의 작성자가 아닙니다"
      redirect_to @article
    end
  end
end

app/views/articles/_card.html.erb
<div class="card m-b-20" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title f-bold"><%= article.title %></h5>
    <p class="card-text m-b-5"><%= truncate(article.description, length: 45) %></p>
    <% if article.categories.any? %>
      <% article.categories.each do |category| %>
        <%= render partial: 'categories/category', locals: { category: category} %>
      <% end %>
    <% end %>
    <div class="button-wrapper m-b-10">
      <%= button_to '보기', article_path(article), method: :get, class: "btn btn-outline-success" %>
      <%= button_to '수정', edit_article_path(article), method: :get, class: "btn btn-outline-info", disabled: (article.user != current_user && !admin?) %>
      <%= button_to '삭제', article_path(article), method: :delete, class: "btn btn-outline-danger", disabled: (article.user != current_user && !admin?) %>
    </div>
    <div class="flex-end">
      <hr />
      <div class="timestamp">
        <p>by <%= link_to article.user.name, user_path(article.user) %></p>
        <%= article.created_at.in_time_zone('Seoul').strftime("%Y/%m/%d %I:%M%p") %>
      </div>
    </div>
  </div>
</div>

<style lang="scss" scoped>
  .card {
      font-family: NotoSans-Regular;
  }

  .card-text {
      line-height: normal;
  }

  .button-wrapper {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
  }

  .timestamp {
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      align-items: center;
      font-size: 12px;
  }

  .flex-end {
      align-self: flex-end;
  }
</style>

app/views/articles/edit.html.erb
<% if @article.errors.any? %>
  <% @article.errors.full_messages.each do |e| %>
    <%= render partial: "commons/errors", locals: { error: e } %>
  <% end %>

<% else %>
  <h2>게시글 수정</h2>
  <%= form_with(model: @article, local: true)  do |f| %>
    <div class="m-b-20">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="m-b-20">
      <%= f.label :description %>
      <%= f.text_area :description, :rows => 10 %>
    </div>

    <div class="m-b-20">
      <%= f.label :category %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, include_hidden: false do |checkbox| %>
        <div class="checkbox_container">
          <%= checkbox.check_box %>
          <%= checkbox.label %>
        </div>
      <% end %>
    </div>

    <div class="m-b-20">
      <%= f.label :user %>
      <%= f.collection_select(:user_id, User.all, :id, :name, {}, { disabled: true }) %>
    </div>

    <div class="m-b-20">
      <div class="flex-row">
        <p class="m-r-5">Updated at: </p>
        <p><%= time_ago_in_words(@article.updated_at) %> ago</p>
      </div>
    </div>

    <%= f.submit '수정', class: "btn btn-outline-info" %>

  <% end %>

<% end %>

<style lang="scss" scoped>
    div {
        width: 300px;
        display: flex;
        flex-direction: column;
    }

    .flex-row {
        display: flex;
        flex-direction: row;
    }

    .checkbox_container {
        display: flex;
        flex-direction: row;
        align-items: center;
    }

    .checkbox_container input {
        margin-right: 5px;
    }

    .checkbox_container label {
        margin: 0;
    }
</style>

app/views/articles/index.html.erb
<div class="flex-row">
  <h1>게시글</h1>
  <%= button_to '작성', new_article_path, method: :get, class: "btn btn-outline-primary m-l-20", disabled: !user_signed_in? %>
</div>


<div class="grid-col2">
  <% @article.each do |article| %>
    <%= render partial: "card", locals: { article: article } %>
  <% end %>
</div>

<%= will_paginate @article, class: "flickr_pagination" %>

<style lang="scss" scoped>
    .grid-col2 {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      column-gap: 20px;
    }

    .flex-row {
        display: flex;
        flex-direction: row;
        align-items: center;
    }
</style>

app/views/articles/new.html.erb
<% if @article.errors.any? %>
  <% @article.errors.full_messages.each do |e| %>
    <%= render partial: "commons/errors", locals: { error: e } %>
  <% end %>
<% else %>
  <h1>게시글 작성</h1>

  <%= form_with scope: :article, url: articles_path, multipart: true, local: true do |f| %>
    <div class="m-b-20">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="m-b-20">
      <%= f.label :description %>
      <%= f.text_area :description, :rows => 10 %>
    </div>

    <div class="m-b-20">
      <%= f.fields_for :post_attachments do |p| %>
        <%= f.label :avatar, 'Photo' %>
        <%= f.file_field :avatar, multiple: true, name: "post_attachments[avatar][]" %>
      <% end %>
    </div>

    <div class="m-b-20">
      <%= f.label :category %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, include_hidden: false do |checkbox| %>
        <div class="checkbox_container">
          <%= checkbox.check_box %>
          <%= checkbox.label %>
        </div>
      <% end %>
    </div>

    <%= f.submit '작성', class: "btn btn-outline-primary" %>

  <% end %>
<% end %>

<style lang="scss" scoped>
  div {
      width: 300px;
      display: flex;
      flex-direction: column;
  }

  .checkbox_container {
      display: flex;
      flex-direction: row;
      align-items: center;
  }

  .checkbox_container input {
      margin-right: 5px;
  }

  .checkbox_container label {
      margin: 0;
  }
</style>

app/views/articles/show.html.erb
<h2>게시글</h2>

<div class="top-area">
  <p class="f-17 f-bold"><%= @article.title %></p>
  <p class="f-12"><%= @article.created_at.in_time_zone('Seoul').strftime("%Y/%m/%d %I:%M%p") %></p>
</div>

<div class="m-b-10">
  <% @article.categories.each do |category| %>
    <%= render partial: 'categories/category', locals: { category: category } %>
  <% end %>
</div>

<% if @article.photos.any? %>
  <%= render partial: 'commons/photo-carousel', locals: { photos: @article.photos } %>
<% end %>

<div class="description">
  <%= simple_format(@article.description) %>
</div>

<div class="bottom-area">
  <p class="f-11">댓글 <%= @comment.count %>개</p>
</div>
<ul>
  <% @comment.each do |c| %>
    <%= render partial: 'comments/comment', locals: { comment: c }%>
  <% end %>
</ul>
<%= will_paginate @comment, class: "digg_pagination" %>
<%= render partial: 'comments/new', locals: { article: @article} %>

<style lang="scss" scoped>
  .top-area {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
      padding: 11px;
      border-top: 1px solid #ccc;
      border-bottom: 1px solid #ccc;
      background: #fcfcfc;
  }

  .bottom-area {
      border: 1px solid #ccc;
      border-radius: 5px;
      background: linear-gradient(to bottom,#fff 0,#f9f9f9 100%);
      padding: 10px;
  }

  .description {
      padding: 11px;
  }

  .block {
      width: 300px;
      display: flex;
      flex-direction: column;
  }

  .checkbox_container {
      display: flex;
      flex-direction: row;
      align-items: center;
  }

  .checkbox_container input {
      margin-right: 5px;
  }

  .checkbox_container label {
      margin: 0;
  }

  ul {
      padding: 0;
  }

  .digg_pagination {
      display: flex;
      justify-content: center;
  }
</style>