config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'
  post 'chatrooms', to: 'chatrooms#create'
  post 'photos', to: 'photos#create'

  resources :users
  resources :articles
  resources :categories, except: [:destroy]
  resources :comments
  resources :chatrooms, only: [:index, :show]
  resources :messages, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
end

app/views/commons/_errors.html.erb
<div class="alert alert-primary" role="alert">
  <%= error %>
</div>

app/views/commons/_footer.html.erb
<footer class="page-footer font-small blue fixed-bottom">
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://github.com/gajagajago"> https://github.com/gajagajago</a>
  </div>
</footer>

app/views/commons/_jumbotron.html.erb
<div class="jumbotron jumbotron-fluid">
  <p class="title f-bold m-l-20">윤희 & 준욜 Private Blog</p>
</div>

<style lang="scss">
  .jumbotron {
      background-image: url('http://photo.vanillabridge.com/banners/couple2.jpeg');
      background-size: cover;
      height: 400px;
  }

  .title {
      font-size: 20px;
      color: #ff90d3;
      font-weight: 500;
  }
</style>

app/views/commons/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path do %>
    <i class="fas fa-heartbeat fa-2x"></i>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">홈 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          메뉴
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to '유저', users_path, class: "dropdown-item" %>
          <%= link_to '게시글', articles_path, class: "dropdown-item" %>
          <%= link_to '카테고리', categories_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to '채팅방', chatrooms_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if !user_signed_in? %>
        <li class="nav-item">
          <%= link_to '로그인', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to '회원가입', new_user_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <% if admin? %>
            <%= link_to '프로필(어드민)', user_path(@current_user), class: "nav-link" %>
        <% else %>
            <%= link_to '프로필', user_path(@current_user), class: "nav-link" %>
        <% end %>
        </li>
        <li class="nav-item">
          <%= link_to '로그아웃', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% end %>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
    </ul>
<!--    <form class="form-inline my-2 my-lg-0">-->
<!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--    </form>-->
  </div>
</nav>

<style lang="scss" scoped>
  .fa-heartbeat {
      color: #ff90d3;
  }
</style>

app/views/commons/_photo-carousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% photos.each_with_index do |p, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
        <%= image_tag(p.photo_url.url, :class => "d-block w-100") %>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>